services:
  postgres:
    container_name: postgres-dental
    image: 'postgres:18'
    environment:
      - 'POSTGRES_DB=dental_clinic'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
